/// Offline Flutter widget reference data model.
/// Generated as a companion to flutter_widget_tree_library.md.

class WidgetReference {
  const WidgetReference({
    required this.category,
    required this.name,
    required this.description,
  });

  final String category;
  final String name;
  final String description;
}

const flutterWidgetReference = <WidgetReference>[
  WidgetReference(category: 'How Flutter Fits Together', name: 'Widget', description: 'Immutable description of part of the UI; Flutter rebuilds widgets to describe the current interface.'),
  WidgetReference(category: 'How Flutter Fits Together', name: 'StatelessWidget', description: 'Widget with no mutable state of its own; rebuilds from inputs.'),
  WidgetReference(category: 'How Flutter Fits Together', name: 'StatefulWidget', description: 'Widget whose associated State can change during its lifetime.'),
  WidgetReference(category: 'How Flutter Fits Together', name: 'State', description: 'Holds mutable UI state; call setState() to request a rebuild.'),
  WidgetReference(category: 'How Flutter Fits Together', name: 'BuildContext', description: 'Location in the widget tree used to read themes, navigation, inherited data, and layout information.'),
  WidgetReference(category: 'How Flutter Fits Together', name: 'Key / ValueKey / ObjectKey / GlobalKey', description: 'Preserve identity when widgets move, reorder, or need state/form access. Use GlobalKey sparingly.'),
  WidgetReference(category: 'How Flutter Fits Together', name: 'InheritedWidget', description: 'Efficiently exposes data to descendants; basis of Theme, MediaQuery, and many state-management tools.'),
  WidgetReference(category: 'How Flutter Fits Together', name: 'Builder', description: 'Creates a fresh BuildContext, often to access an ancestor inserted just above it.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'runApp', description: 'Starts Flutter and attaches the root widget to the screen.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'MaterialApp', description: 'Material app shell: theme, routes, localization, navigator, and default behaviors.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'CupertinoApp', description: 'Apple-style app shell with Cupertino navigation and defaults.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'WidgetsApp', description: 'Lower-level app shell used when you do not want Material or Cupertino defaults.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'Scaffold', description: 'Standard Material page frame: app bar, body, drawer, FAB, bottom navigation, sheets, snack bars.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'SafeArea', description: 'Pads content away from notches, status bars, gesture areas, and system UI.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'AppBar', description: 'Top Material bar for title, navigation, actions, tabs, and search.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'SliverAppBar', description: 'Collapsing/pinned/floating app bar used inside CustomScrollView.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'NavigationBar', description: 'Material 3 bottom destination selector.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'NavigationRail', description: 'Side destination selector for wide/tablet/desktop layouts.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'BottomAppBar', description: 'Bottom surface often used with a FloatingActionButton notch.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'Drawer / NavigationDrawer', description: 'Side navigation panel; NavigationDrawer is the Material 3 version.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'FloatingActionButton', description: 'Prominent primary action button, usually attached to Scaffold.'),
  WidgetReference(category: 'App Roots & Screen Structure', name: 'PersistentFooterButtons', description: 'Legacy Scaffold footer action row; prefer BottomAppBar or bottom sheets in new designs.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'Row', description: 'Places children horizontally; use mainAxisAlignment and crossAxisAlignment to position them.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'Column', description: 'Places children vertically; constrain or scroll it when its contents can exceed screen height.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'Flex', description: 'General Row/Column; choose Axis.horizontal or Axis.vertical.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'Wrap', description: 'Flows children onto new lines when there is not enough room; useful for chips and tags.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'Stack', description: 'Paints children on top of one another; use for overlays, badges, and layered UIs.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'IndexedStack', description: 'Shows one child while keeping the other children alive.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'Flow', description: 'Advanced, paint-time child positioning via FlowDelegate.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'Table', description: 'Grid-like rows and columns with table sizing rules.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'CustomMultiChildLayout', description: 'Advanced multi-child layout controlled by a delegate.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'LayoutBuilder', description: 'Builds based on the parent’s constraints; core tool for responsive layout.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'OrientationBuilder', description: 'Builds differently for portrait versus landscape orientation.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'MediaQuery', description: 'Reads screen size, padding, text scaling, platform brightness, and other device context.'),
  WidgetReference(category: 'Layout: Multi-child Parents', name: 'Placeholder', description: 'Draws a visual placeholder during layout prototyping.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'Container', description: 'Convenience box for padding, margin, constraints, decoration, alignment, transform, and child.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'Padding', description: 'Adds empty space around one child.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'Align', description: 'Aligns a child inside itself; can optionally size itself to the child.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'Center', description: 'Shorthand for Align(alignment: Alignment.center).'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'SizedBox', description: 'Gives a child fixed width/height or adds fixed blank space.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'ConstrainedBox', description: 'Adds minimum/maximum size constraints to a child.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'UnconstrainedBox', description: 'Removes selected parent constraints; use carefully because overflow is possible.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'LimitedBox', description: 'Applies maximum size only when incoming constraints are unbounded.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'FractionallySizedBox', description: 'Sizes child as a fraction of available space.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'AspectRatio', description: 'Sizes a child to a chosen width-to-height ratio.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'FittedBox', description: 'Scales and positions a child to fit within available bounds.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'Expanded', description: 'Row/Column/Flex child that must fill remaining main-axis space.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'Flexible', description: 'Row/Column/Flex child allowed to use flexible space without necessarily filling it.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'Spacer', description: 'Flexible empty space in a Row, Column, or Flex.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'Baseline', description: 'Aligns a child to a specific text baseline.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'IntrinsicWidth / IntrinsicHeight', description: 'Sizes based on child intrinsic dimensions; expensive—avoid in large lists.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'OverflowBox', description: 'Lets child exceed parent constraints intentionally.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'Offstage', description: 'Lays out but does not paint/hit-test a child; remove inactive widgets instead when possible.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'Visibility', description: 'Shows, hides, or preserves layout/state of a child with configurable behavior.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'IgnorePointer', description: 'Makes descendants ignore pointer events while still painting them.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'AbsorbPointer', description: 'Consumes pointer events so descendants do not receive them.'),
  WidgetReference(category: 'Layout: Single-child Positioning & Sizing', name: 'ExcludeFocus', description: 'Prevents a subtree from receiving focus.'),
  WidgetReference(category: 'Positioning Inside a Stack', name: 'Positioned', description: 'Sets a Stack child’s left/top/right/bottom/width/height; must be under Stack.'),
  WidgetReference(category: 'Positioning Inside a Stack', name: 'Positioned.fill', description: 'Makes a Stack child fill all available stack space.'),
  WidgetReference(category: 'Positioning Inside a Stack', name: 'PositionedDirectional', description: 'Uses start/end rather than left/right for RTL-safe placement.'),
  WidgetReference(category: 'Positioning Inside a Stack', name: 'Align', description: 'Often simpler than Positioned when only alignment is needed in a Stack.'),
  WidgetReference(category: 'Positioning Inside a Stack', name: 'AnimatedPositioned', description: 'Implicitly animates a child’s Positioned values.'),
  WidgetReference(category: 'Positioning Inside a Stack', name: 'Draggable', description: 'Lets a child be dragged; pair with DragTarget to accept drops.'),
  WidgetReference(category: 'Positioning Inside a Stack', name: 'DragTarget', description: 'Receives data from a Draggable when dropped over it.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'Text', description: 'Displays one styled run of text.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'RichText', description: 'Displays multiple text styles using a TextSpan tree.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'Text.rich', description: 'Convenience Text constructor for inline TextSpan content.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'SelectableText', description: 'Text users can select and copy.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'DefaultTextStyle', description: 'Provides default text style to descendant Text widgets.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'TextField', description: 'Editable text input; use controller, focusNode, decoration, keyboardType, validator via TextFormField.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'EditableText', description: 'Low-level editable text engine behind TextField; rarely needed directly.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'Icon', description: 'Displays an icon from an IconData source.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'IconButton', description: 'Tappable icon button with Material behavior and accessibility label.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'Image', description: 'Base image widget; use constructors below for common image sources.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'Image.asset', description: 'Displays an image bundled in your app assets.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'Image.network', description: 'Displays an image downloaded from a URL.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'Image.file', description: 'Displays an image from a local file (not web).'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'Image.memory', description: 'Displays an image from bytes in memory.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'AssetImage', description: 'ImageProvider for a bundled asset.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'NetworkImage', description: 'ImageProvider for a network image.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'FadeInImage', description: 'Shows placeholder then fades in the loaded image.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'CircleAvatar', description: 'Circular avatar, often with image/background and initials.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'FlutterLogo', description: 'Flutter logo widget for demos; follow Flutter branding guidance.'),
  WidgetReference(category: 'Text, Icons, Images & Assets', name: 'AssetBundle', description: 'Loads text, binary assets, and structured data packaged with the app.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'DecoratedBox', description: 'Paints a Decoration (color, border, gradient, shadow) behind or in front of a child.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'ColoredBox', description: 'Efficient solid-color background for a child.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'Card', description: 'Material elevated/outlined container for grouped content.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'Material', description: 'Material surface that supplies ink effects, elevation, shape, and color.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'Ink', description: 'Paints decoration on a Material surface so ink splashes remain visible.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'InkWell', description: 'Material tap/hover splash response; requires a Material ancestor for visible ink.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'InkResponse', description: 'Lower-level flexible ink reaction, including circular splashes.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'ClipRRect', description: 'Clips child to a rounded rectangle.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'ClipOval', description: 'Clips child to an oval/circle.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'ClipPath', description: 'Clips child using a custom path.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'ClipRect', description: 'Clips child to a rectangle.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'Opacity', description: 'Applies opacity; AnimatedOpacity for transitions. May be costly in some cases.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'ShaderMask', description: 'Applies a shader, such as a gradient, to a child.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'ColorFiltered', description: 'Applies a color filter to a child.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'BackdropFilter', description: 'Filters content behind this widget; useful for blur/glass effects.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'Transform', description: 'Applies translation, scale, rotation, skew, or custom matrix at paint time.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'RotatedBox', description: 'Rotates in quarter turns during layout; preferable to Transform.rotate for 90° turns.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'CustomPaint', description: 'Paints custom graphics with a CustomPainter.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'RepaintBoundary', description: 'Isolates paint work; use only after profiling shows a repaint problem.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'PhysicalModel / PhysicalShape', description: 'Clips and paints a physical elevation/shadow shape.'),
  WidgetReference(category: 'Styling, Surfaces, Painting & Effects', name: 'Divider / VerticalDivider', description: 'Thin Material separator in vertical/horizontal layouts.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'ElevatedButton', description: 'Prominent filled Material button, suited to important actions.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'FilledButton', description: 'Material 3 filled button for primary actions.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'FilledButton.tonal', description: 'Material 3 softer filled button for secondary emphasis.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'OutlinedButton', description: 'Bordered Material button for secondary actions.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'TextButton', description: 'Low-emphasis text-only Material button.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'IconButton', description: 'Icon-only action button; provide tooltip and semantic label where appropriate.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'FloatingActionButton', description: 'Circular primary action button.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'SegmentedButton', description: 'Material 3 single- or multi-select segmented controls.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'DropdownButton', description: 'Classic Material dropdown menu.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'DropdownMenu', description: 'Material 3 dropdown/select field with improved menu behavior.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'MenuAnchor', description: 'Anchors a Material menu to a widget.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'MenuBar', description: 'Desktop-style horizontal menu bar.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'PopupMenuButton', description: 'Displays a popup menu from a button.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'GestureDetector', description: 'Detects taps, drags, long presses, pans, scales, and more without visual feedback.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'Listener', description: 'Low-level pointer event listener (down/move/up/hover).'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'MouseRegion', description: 'Receives mouse enter/exit/hover and changes cursor.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'FocusableActionDetector', description: 'Combines focus, shortcuts/actions, hover, and enabled-state handling for custom controls.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'Dismissible', description: 'Swipe-to-dismiss a list item; supply a stable key.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'Tooltip', description: 'Small explanatory label on long press/hover.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'Shortcuts', description: 'Maps key combinations to Intents in a subtree.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'Actions', description: 'Maps Intents to executable Actions.'),
  WidgetReference(category: 'Buttons, Gestures & User Interaction', name: 'CallbackShortcuts', description: 'Compact shortcut mapping for common keyboard actions.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'Form', description: 'Groups form fields and enables validation/save/reset through FormState or GlobalKey.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'TextFormField', description: 'TextField integrated with Form validation and saving.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'FormField', description: 'Base class for custom fields that participate in a Form.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'Checkbox', description: 'Binary checked/unchecked control; use tristate for a nullable third state.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'CheckboxListTile', description: 'Checkbox with built-in labeled list row.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'Radio', description: 'Single selection from a group; use RadioGroup where available in your SDK.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'RadioListTile', description: 'Radio with a labeled list row.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'Switch', description: 'On/off control.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'SwitchListTile', description: 'Switch with a labeled list row.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'Slider', description: 'Selects a single numeric value from a range.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'RangeSlider', description: 'Selects lower and upper values from a range.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'ChoiceChip', description: 'Selectable compact option, usually single-select.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'FilterChip', description: 'Selectable compact option, often multi-select.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'ActionChip', description: 'Compact action button styled as a chip.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'InputChip', description: 'Chip representing a complex item with selection/deletion/action options.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'Chip', description: 'Compact informational element, such as a contact or tag.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'showDatePicker', description: 'Material modal date picker function.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'showTimePicker', description: 'Material modal time picker function.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'showDateRangePicker', description: 'Material modal date-range picker function.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'Autocomplete', description: 'Text input with suggested options.'),
  WidgetReference(category: 'Forms, Selection & Pickers', name: 'RawAutocomplete', description: 'Lower-level customizable autocomplete.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'SingleChildScrollView', description: 'Scrolls one child; use for modest content, not huge or lazy lists.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'ListView', description: 'Linear scrollable list; use .builder for large/dynamic data.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'ListView.builder', description: 'Lazily creates list children as they become visible.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'ListView.separated', description: 'Lazy list with separators between items.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'GridView', description: 'Scrollable grid; use .builder for large/dynamic data.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'GridView.builder', description: 'Lazily creates grid items.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'PageView', description: 'Scrollable page-by-page content, such as onboarding or tabs.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'PageView.builder', description: 'Lazy PageView for many pages.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'ReorderableListView', description: 'List whose items users reorder by dragging.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'AnimatedList', description: 'List that animates item insertion/removal.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'AnimatedGrid', description: 'Grid that animates item insertion/removal.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'RefreshIndicator', description: 'Material pull-to-refresh wrapper around a vertical scrollable.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'Scrollbar', description: 'Visual scroll thumb for a scrollable.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'ScrollConfiguration', description: 'Changes scrolling behavior/overscroll effect for a subtree.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'ScrollController', description: 'Reads/controls scroll position; dispose when owned by State.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'NotificationListener<ScrollNotification>', description: 'Observes notifications bubbling up from scrolling children.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'DraggableScrollableSheet', description: 'Bottom-sheet-like scrollable that grows/shrinks as user drags.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'NestedScrollView', description: 'Coordinates outer and inner scroll views, often with SliverAppBar + tabs.'),
  WidgetReference(category: 'Lists, Grids & Standard Scrolling', name: 'CarouselView', description: 'Material carousel displaying scrollable items with dynamically changing size.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'CustomScrollView', description: 'Scroll view composed of slivers; use for mixed collapsing headers, lists, grids, and fill areas.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverAppBar', description: 'Collapsible/floating/pinned Material app bar sliver.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverList', description: 'Lazy linear list sliver.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverGrid', description: 'Lazy grid sliver.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverToBoxAdapter', description: 'Places one normal box widget inside a sliver list.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverPadding', description: 'Adds padding around a sliver.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverPersistentHeader', description: 'Pinned/floating/shrinking custom header via a delegate.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverFillRemaining', description: 'Fills remaining viewport space, optionally scrollable.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverFillViewport', description: 'Sizes each child to fill the viewport.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverAnimatedList', description: 'Animated insertion/removal for sliver list items.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverAnimatedGrid', description: 'Animated insertion/removal for sliver grid items.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverVisibility', description: 'Controls visibility of a sliver.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverOffstage', description: 'Lays out a sliver without painting it.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverOpacity', description: 'Applies opacity to a sliver.'),
  WidgetReference(category: 'Slivers: High-performance Custom Scroll Effects', name: 'SliverLayoutBuilder', description: 'Builds a sliver based on sliver constraints.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'Navigator', description: 'Manages a stack of routes/screens; use push, pop, pushNamed, or declarative routing.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'MaterialPageRoute', description: 'Standard Material page transition route.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'CupertinoPageRoute', description: 'iOS-style page transition route.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'PageRouteBuilder', description: 'Custom page route transition.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'RouteObserver', description: 'Observes route changes; useful for screen analytics/lifecycle integration.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'Router', description: 'Declarative routing foundation for URL/web/deep-link-aware navigation.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'MaterialApp.router', description: 'Material app configured with Router rather than simple routes.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'NavigationBar', description: 'Bottom navigation for top-level destinations.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'NavigationRail', description: 'Side navigation for wider windows.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'TabBar', description: 'Tab selector; usually needs DefaultTabController or a TabController.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'TabBarView', description: 'Pages corresponding to TabBar tabs.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'DefaultTabController', description: 'Convenience controller for a descendant TabBar and TabBarView.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'showDialog', description: 'Displays modal dialog above current route.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'AlertDialog', description: 'Standard Material confirmation/information dialog.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'SimpleDialog', description: 'Material dialog for choosing from a small set of options.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'showModalBottomSheet', description: 'Displays a modal sheet from the bottom.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'showBottomSheet', description: 'Displays a persistent sheet attached to a Scaffold.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'SnackBar', description: 'Brief Material message, usually shown via ScaffoldMessenger.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'ScaffoldMessenger', description: 'Shows SnackBars and MaterialBanners above current Scaffold.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'MaterialBanner', description: 'Persistent inline message/action near top of Scaffold.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'Overlay', description: 'Stack above routes for custom transient UI like coach marks or menus.'),
  WidgetReference(category: 'Navigation, Routes & Overlays', name: 'OverlayEntry', description: 'One insertable item in an Overlay.'),
  WidgetReference(category: 'Async, State Flow & Data-dependent UI', name: 'FutureBuilder', description: 'Builds from an asynchronous Future snapshot; create the Future outside build when it should not restart.'),
  WidgetReference(category: 'Async, State Flow & Data-dependent UI', name: 'StreamBuilder', description: 'Builds from values/errors/states emitted by a Stream.'),
  WidgetReference(category: 'Async, State Flow & Data-dependent UI', name: 'ValueListenableBuilder', description: 'Rebuilds from a ValueListenable such as ValueNotifier.'),
  WidgetReference(category: 'Async, State Flow & Data-dependent UI', name: 'AnimatedBuilder', description: 'Rebuilds from any Listenable; useful for explicit animations and controllers.'),
  WidgetReference(category: 'Async, State Flow & Data-dependent UI', name: 'ListenableBuilder', description: 'Rebuilds from a Listenable without animation semantics.'),
  WidgetReference(category: 'Async, State Flow & Data-dependent UI', name: 'InheritedNotifier', description: 'InheritedWidget that notifies dependents when a Listenable changes.'),
  WidgetReference(category: 'Async, State Flow & Data-dependent UI', name: 'NotificationListener', description: 'Observes subtree notifications; different from state management.'),
  WidgetReference(category: 'Async, State Flow & Data-dependent UI', name: 'ChangeNotifier', description: 'Simple observable model object; not a widget, commonly used with provider-style patterns.'),
  WidgetReference(category: 'Async, State Flow & Data-dependent UI', name: 'ValueNotifier', description: 'Small ChangeNotifier that exposes one value.'),
  WidgetReference(category: 'Async, State Flow & Data-dependent UI', name: 'StatefulBuilder', description: 'Creates local setState for a small subtree, commonly inside dialogs; keep it limited.'),
  WidgetReference(category: 'Animation & Motion', name: 'AnimatedContainer', description: 'Implicitly animates Container properties such as size, color, padding, alignment, decoration.'),
  WidgetReference(category: 'Animation & Motion', name: 'AnimatedOpacity', description: 'Implicitly fades child opacity.'),
  WidgetReference(category: 'Animation & Motion', name: 'AnimatedAlign', description: 'Implicitly animates alignment.'),
  WidgetReference(category: 'Animation & Motion', name: 'AnimatedPadding', description: 'Implicitly animates padding.'),
  WidgetReference(category: 'Animation & Motion', name: 'AnimatedPositioned', description: 'Implicitly animates a Positioned Stack child.'),
  WidgetReference(category: 'Animation & Motion', name: 'AnimatedSize', description: 'Animates when child size changes.'),
  WidgetReference(category: 'Animation & Motion', name: 'AnimatedSwitcher', description: 'Animates when a child is replaced; use keys to distinguish same-type children.'),
  WidgetReference(category: 'Animation & Motion', name: 'AnimatedCrossFade', description: 'Cross-fades between two children and animates size.'),
  WidgetReference(category: 'Animation & Motion', name: 'AnimatedScale / AnimatedRotation / AnimatedSlide', description: 'Implicitly animate transform-like scale, rotation, or offset.'),
  WidgetReference(category: 'Animation & Motion', name: 'TweenAnimationBuilder', description: 'Builds a simple implicit tween without managing a controller.'),
  WidgetReference(category: 'Animation & Motion', name: 'Hero', description: 'Shared-element transition between routes using matching tags.'),
  WidgetReference(category: 'Animation & Motion', name: 'AnimationController', description: 'Controls explicit animation timeline; dispose it in State.'),
  WidgetReference(category: 'Animation & Motion', name: 'Animation', description: 'Read-only animated value driven by controller/tween.'),
  WidgetReference(category: 'Animation & Motion', name: 'Tween', description: 'Maps normalized animation progress to a value range.'),
  WidgetReference(category: 'Animation & Motion', name: 'CurvedAnimation', description: 'Applies a curve to an animation.'),
  WidgetReference(category: 'Animation & Motion', name: 'FadeTransition', description: 'Explicit animation of opacity.'),
  WidgetReference(category: 'Animation & Motion', name: 'ScaleTransition', description: 'Explicit animation of scale.'),
  WidgetReference(category: 'Animation & Motion', name: 'RotationTransition', description: 'Explicit animation of rotation.'),
  WidgetReference(category: 'Animation & Motion', name: 'SlideTransition', description: 'Explicit animation of fractional offset.'),
  WidgetReference(category: 'Animation & Motion', name: 'SizeTransition', description: 'Explicit animation of size along one axis.'),
  WidgetReference(category: 'Animation & Motion', name: 'PositionedTransition', description: 'Explicit animation of a Stack child’s relative rectangle.'),
  WidgetReference(category: 'Animation & Motion', name: 'DecoratedBoxTransition', description: 'Explicit animation between decorations.'),
  WidgetReference(category: 'Animation & Motion', name: 'AnimatedModalBarrier', description: 'Animated barrier that blocks interactions behind modal UI.'),
  WidgetReference(category: 'Animation & Motion', name: 'TickerMode', description: 'Disables ticking animations in an inactive subtree.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'Theme', description: 'Supplies Material design values to descendants.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'ThemeData', description: 'Material theme configuration: color scheme, typography, components, visual density.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'ColorScheme', description: 'Semantic Material color palette; prefer it over scattered literal colors.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'TextTheme', description: 'Named text styles for consistent typography.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'IconTheme', description: 'Default icon color, opacity, and size for descendants.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'DefaultTextStyle', description: 'Default text style for descendants.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'MediaQuery', description: 'Device/window data including size, padding, accessibility and text scale.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'LayoutBuilder', description: 'Responds to parent constraints—usually better than only checking screen width.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'Directionality', description: 'Supplies text direction (LTR/RTL) to descendants.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'Localizations', description: 'Provides localized resources to the widget subtree.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'Localizations.override', description: 'Overrides locale/resources for a subtree.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'MaterialApp.localizationsDelegates', description: 'Registers localization delegates in a Material app.'),
  WidgetReference(category: 'Theme, Responsive Design & Internationalization', name: 'MediaQuery.textScalerOf', description: 'Reads user text scaling preference; avoid hard-coding text size behavior.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'Semantics', description: 'Adds a meaningful accessibility label, role, value, hint, or action to a subtree.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'MergeSemantics', description: 'Combines descendant semantics into one accessible node.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'ExcludeSemantics', description: 'Removes descendant semantics from assistive technologies.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'ExcludeFocus', description: 'Prevents focus for a subtree.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'Focus', description: 'Makes a widget/subtree focusable and handles focus changes.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'FocusScope', description: 'Groups focusable widgets and controls focus traversal.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'FocusTraversalGroup', description: 'Defines traversal order for a group of focusable widgets.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'FocusTraversalOrder', description: 'Overrides traversal order of an individual widget.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'KeyboardListener', description: 'Receives raw keyboard events for focused hardware keyboard input.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'Shortcuts', description: 'Maps keyboard shortcuts to semantic Intents.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'Actions', description: 'Maps Intents to Actions that execute behavior.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'FocusableActionDetector', description: 'Accessible base for custom buttons: focus, hover, shortcuts, and enabled state.'),
  WidgetReference(category: 'Accessibility, Focus & Keyboard', name: 'Tooltip', description: 'Explains controls on hover or long press.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoApp', description: 'App shell with iOS-style defaults.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoPageScaffold', description: 'Basic iOS-style page with navigation bar and child content.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoNavigationBar', description: 'iOS-style top navigation bar.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoSliverNavigationBar', description: 'Large-title/sliver iOS navigation bar.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoTabScaffold', description: 'iOS bottom-tab application shell.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoTabBar', description: 'Bottom tab selector for CupertinoTabScaffold.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoTabView', description: 'Independent Navigator for a Cupertino tab.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoButton', description: 'iOS-style button.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoTextField', description: 'iOS-style text field.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoSwitch', description: 'iOS-style switch.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoSlider', description: 'iOS-style numeric slider.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoPicker', description: 'iOS wheel picker.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoDatePicker', description: 'iOS date/time wheel picker.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoActionSheet', description: 'iOS action sheet, usually shown by showCupertinoModalPopup.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoAlertDialog', description: 'iOS confirmation/information dialog.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoDialogAction', description: 'Action button used in CupertinoAlertDialog.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoActivityIndicator', description: 'iOS loading spinner.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoListSection', description: 'iOS grouped-list section.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoListTile', description: 'iOS-style list row.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoScrollbar', description: 'iOS-style scrollbar.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoContextMenu', description: 'Long-press context menu with preview/action UI.'),
  WidgetReference(category: 'Cupertino (iOS/macOS Style)', name: 'CupertinoSearchTextField', description: 'iOS-style search field.'),
  WidgetReference(category: 'Platform, Desktop & Adaptive Helpers', name: 'PlatformView', description: 'Embeds a native platform view; use deliberately because it has performance/interaction trade-offs.'),
  WidgetReference(category: 'Platform, Desktop & Adaptive Helpers', name: 'AndroidView', description: 'Embeds an Android native view.'),
  WidgetReference(category: 'Platform, Desktop & Adaptive Helpers', name: 'UiKitView', description: 'Embeds an iOS UIKit view.'),
  WidgetReference(category: 'Platform, Desktop & Adaptive Helpers', name: 'PlatformMenuBar', description: 'Native macOS menu bar integration.'),
  WidgetReference(category: 'Platform, Desktop & Adaptive Helpers', name: 'MenuBar', description: 'Flutter Material desktop menu bar.'),
  WidgetReference(category: 'Platform, Desktop & Adaptive Helpers', name: 'WindowSizeClass', description: 'Concept, not a core widget: adapt layout based on available width/height, normally via LayoutBuilder.'),
  WidgetReference(category: 'Platform, Desktop & Adaptive Helpers', name: 'SelectionArea', description: 'Makes an entire subtree text-selectable on supported platforms.'),
  WidgetReference(category: 'Platform, Desktop & Adaptive Helpers', name: 'InteractiveViewer', description: 'Pan/zoom a child with gestures; useful for diagrams/maps/canvases.'),
  WidgetReference(category: 'Platform, Desktop & Adaptive Helpers', name: 'DataTable', description: 'Material table for small/medium datasets; use paginated/lazy patterns for large data.'),
  WidgetReference(category: 'Platform, Desktop & Adaptive Helpers', name: 'PaginatedDataTable', description: 'DataTable with pagination.'),
  WidgetReference(category: 'Platform, Desktop & Adaptive Helpers', name: 'TableView', description: 'Two-dimensional scrollable table view where supported by current Flutter SDK.'),
  WidgetReference(category: 'Loading, Feedback & Common Status UI', name: 'CircularProgressIndicator', description: 'Circular indeterminate or determinate progress indicator.'),
  WidgetReference(category: 'Loading, Feedback & Common Status UI', name: 'LinearProgressIndicator', description: 'Horizontal progress indicator.'),
  WidgetReference(category: 'Loading, Feedback & Common Status UI', name: 'RefreshProgressIndicator', description: 'Material spinner typically used by RefreshIndicator.'),
  WidgetReference(category: 'Loading, Feedback & Common Status UI', name: 'AdaptiveProgressIndicator', description: 'Use adaptive constructors/components where platform-specific appearance matters.'),
  WidgetReference(category: 'Loading, Feedback & Common Status UI', name: 'Badge', description: 'Small Material indicator/count attached to another widget.'),
  WidgetReference(category: 'Loading, Feedback & Common Status UI', name: 'Banner', description: 'Diagonal ribbon label over a child.'),
  WidgetReference(category: 'Loading, Feedback & Common Status UI', name: 'Tooltip', description: 'Explains a control without taking permanent layout space.'),
  WidgetReference(category: 'Loading, Feedback & Common Status UI', name: 'SnackBar', description: 'Short feedback message.'),
  WidgetReference(category: 'Loading, Feedback & Common Status UI', name: 'MaterialBanner', description: 'Persistent feedback/action message near top of a screen.'),
  WidgetReference(category: 'Loading, Feedback & Common Status UI', name: 'AlertDialog', description: 'Blocks for acknowledgement, confirmation, or a focused decision.'),
  WidgetReference(category: 'Loading, Feedback & Common Status UI', name: 'Empty state pattern', description: 'Usually a centered Column with Icon/Image, Text, explanation, and a retry/action button—not a single built-in widget.'),
  WidgetReference(category: 'Practical Parent/Child Rules', name: 'Expanded / Flexible / Spacer → Row, Column, or Flex', description: 'These are ParentDataWidgets and require a Flex ancestor without render-object widgets in between.'),
  WidgetReference(category: 'Practical Parent/Child Rules', name: 'Positioned → Stack', description: 'Positioned must be a descendant of Stack; do not place it in Row/Column.'),
  WidgetReference(category: 'Practical Parent/Child Rules', name: 'Sliver* widgets → CustomScrollView', description: 'Use slivers only in sliver-aware parents, usually CustomScrollView.'),
  WidgetReference(category: 'Practical Parent/Child Rules', name: 'TabBar + TabBarView → DefaultTabController or TabController', description: 'Both must use the same controller and have matching tab/page counts.'),
  WidgetReference(category: 'Practical Parent/Child Rules', name: 'ScaffoldMessenger → Scaffold / MaterialApp', description: 'Use it to show SnackBars rather than calling deprecated Scaffold.of patterns.'),
  WidgetReference(category: 'Practical Parent/Child Rules', name: 'InkWell → Material', description: 'Ink splash needs a Material ancestor; use Ink for decorated surfaces.'),
  WidgetReference(category: 'Practical Parent/Child Rules', name: 'FormField / TextFormField → Form', description: 'A Form is required when you want group validation/save/reset.'),
  WidgetReference(category: 'Practical Parent/Child Rules', name: 'Dismissible → stable Key', description: 'Each list item needs a unique key so Flutter tracks the correct item.'),
  WidgetReference(category: 'Practical Parent/Child Rules', name: 'ReorderableListView → stable keys', description: 'Every reorderable child needs a key.'),
  WidgetReference(category: 'Practical Parent/Child Rules', name: 'ListView inside Column', description: 'Wrap ListView in Expanded/Flexible or give it a bounded height to avoid unbounded-height errors.'),
  WidgetReference(category: 'Practical Parent/Child Rules', name: 'SingleChildScrollView + Column', description: 'Use for short content; do not put an unbounded ListView inside it without careful constraints.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need a normal page?', description: 'Scaffold + SafeArea + AppBar + body.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need horizontal/vertical arrangement?', description: 'Row / Column; add Expanded, Flexible, Spacer, or Wrap as needed.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need a responsive breakpoint?', description: 'LayoutBuilder first; use MediaQuery for global window/device properties.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need a large list?', description: 'ListView.builder; use CustomScrollView + SliverList when mixing lists with sliver headers/grids.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need fixed card-like content?', description: 'Card or Container/DecoratedBox with Material/Ink interactions.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need a button?', description: 'FilledButton for primary, OutlinedButton for secondary, TextButton for low emphasis, IconButton for icon action.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need a form?', description: 'Form + TextFormField/other FormField widgets + validator.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need async data?', description: 'FutureBuilder for a one-time Future; StreamBuilder for ongoing updates.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need a simple animation?', description: 'Start with implicit widgets: AnimatedContainer, AnimatedOpacity, AnimatedSwitcher.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need custom animation control?', description: 'AnimationController + Transition widgets/AnimatedBuilder.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need iOS-native visual language?', description: 'Use CupertinoApp and Cupertino widgets consistently for that subtree/app.'),
  WidgetReference(category: 'Fast Selection Guide', name: 'Need custom drawing?', description: 'CustomPaint + CustomPainter, after exhausting composition with standard widgets.'),
];
